name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: |
          # Example: Run ESLint for JavaScript files
          npx eslint . --ext .js
          # Add other linters as needed

      - name: Run tests
        run: |
          # Example: Run Jest tests
          npx jest
          # Add other test runners as needed

      - name: Build project
        run: |
          # Example: Build the project (if applicable)
          npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
