name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Environment
        run: echo "Setting up the environment..."

      - name: Run Tests
        run: echo "Running tests..."

      - name: Build Application
        run: echo "Building application..."

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    if: success() 
    environment:
      name: sample
      url: http://127.0.0.1:5500/todolist.html
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: echo "Deploying to production..."
